# Generated by Django 4.2.7 on 2023-12-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='img/%Y/ %m/ %d'),
            preserve_default=False,
        ),
    ]
